include:
  # - bind9/docker-compose.yml
  - homepage/docker-compose.yml
  - authentik/docker-compose.yml
  - crowdsec/docker-compose.yml
  - socket-proxy/docker-compose.yml
  - traefik/docker-compose.yml
  - diun/docker-compose.yml
    # - portainer/docker-compose.yml # Container management
  # - watchtower/docker-compose.yml # Container auto-updator


networks:
  crowdsec:
    driver: bridge
  default:
    driver: bridge
  diun:
    driver: bridge
  homepage:
    driver: bridge
  socket-proxy:
    name: socket-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  watchtower:
    driver: bridge