services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - "8080:8080"
    environment:
      - TZ=${TZ}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/etc/traefik/acme.json
      - ./config.yml:/config.yml:ro
      - ./logs:/var/log/traefik
    networks:
      crowdsec:
      diun:
      homepage:
      socket-proxy:
      traefik:
        ipv4_address: 192.168.90.254
    depends_on:
      crowdsec:
        condition: service_started
      bouncer-traefik:
        condition: service_healthy
      server:
        condition: service_healthy
    labels:
      - "crowdsec.enable=true"
      - "crowdsec.labels.type=traefik"
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=chain-no-auth@file"
      - "traefik.http.routers.traefik-api.entrypoints=websecure"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.routers.traefik-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.middlewares=chain-no-auth@file"
      - "homepage.group=Security"
      - "homepage.name=Traefik"
      - "homepage.icon=traefik.png"
      - "homepage.href=https://traefik.${DOMAIN}"
      - "homepage.description=Reverse proxy"
      - "homepage.widget.type=traefik"
      - "homepage.widget.url=http://traefik:8080"
    security_opt:
      - no-new-privileges:true

networks:
  crowdsec:
    external: true
  diun:
    external: true
  homepage:
    external: true
  socket-proxy:
    external: true
  traefik:
    external: true