---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks
#
- Bookmarks:
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com
          description: YouTube
    - Homepage:
        - abbr: HP
          href: https://gethomepage.dev/
    - Endevouros:
        - abbr: EOS
          href: https://forum.endeavouros.com/
